deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  permissions:
    id-token: write #This is required for requesting the JWT
    contents: read #This is required for actions/checkout

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Unzip artifact for deployment
      run: unzip release.zip
    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F9B788E88FC64FF4AF03EDA652B13F8C }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_17CDFD8DD27345BC99F0E9B1AB8B0C15 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_44434F4649B44CD6B318330143E7219C }}

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'learning-adonisjs-app'
        slot-name: 'Production'
        package: .
    
  env:
    APP_KEY: ${{ vars.APP_KEY }}
    HOST: ${{ vars.HOST }}
    #MONGO_URL: ${{ secrets.MONGO_URL }}
    #PORT: ${{ vars.PORT }}
